export const modelNames = {
  // Entity table names (singular)
  USER: 'user',
  MOVIE: 'movie',
  PAYMENT: 'payment',
  CHAT: 'chat',
  FEEDBACK: 'feedback',
  SEARCH_HISTORY: 'search_history',
  WALLET: 'wallet',
  VOUCHER: 'voucher',
  USER_VOUCHER: 'user_voucher',
  PERSON: 'person',
  GENRE: 'genre',
  WATCH_HISTORY: 'watch_history',
  IMAGE: 'image',
  VIDEO: 'video',
  TOPIC: 'topic',
  LANGUAGE: 'language',
  KEYWORD: 'keyword',
  WATCH_PROVIDER: 'watch_provider',
  MOVIE_WATCH_PROVIDER: 'movie_watch_provider',
  PRODUCTION_COMPANY: 'production_company',
  MOVIE_PURCHASE: 'movie_purchase',
  MOVIE_CAST: 'movie_cast',
  MOVIE_CREW: 'movie_crew',
  WATCH_PARTY: 'watch_party',
  TICKET: 'ticket',
  TICKET_PURCHASE: 'ticket_purchase',
  WATCH_PARTY_LOG: 'watch_party_log',
  WATCH_PARTY_LIKE: 'watch_party_like',

  // Join table names (using singular entity names)
  USER_FAVORITE_MOVIES: 'user_favorite_movie',
  MOVIE_GENRES: 'movie_genre',
  MOVIE_KEYWORDS: 'movie_keyword',
  MOVIE_PRODUCTION_COMPANIES: 'movie_production_company',
  MOVIE_SPOKEN_LANGUAGE: 'movie_spoken_languages',
};
